// autogenerated by typings-for-css-modules-loader.
// Please do not change this file!
declare namespace StylesCssModule {
  export interface IStylesCss {
    folderViewer: string;
    listItem: string;
  }
}

declare const StylesCssModule: StylesCssModule.IStylesCss & {
  /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
  locals: StylesCssModule.IStylesCss;
};

export = StylesCssModule;
